// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:cure/features/auth/data/models/user_model.dart';
import 'package:cure/features/home/data/models/service_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ServiceModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ServiceModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
